### ISSUE TITLE
Failing to decode record type referencing an enum

### ISSUE THREAD

**Issue by ajayrathore** [gklijs/schema_registry_converter#19]
My schema looks like this

```
[
  {
    "type": "enum",
    "name": "myflag",
    "namespace": "myns",
    "symbols": [
      "A",
      "B",
      "C"
    ]
  },
  {
    "type": "record",
    "name": "mymsg",
    "namespace": "myns",
    "fields": [
      {
        "name": "myid",
        "type": "int"
      },
      {
        "name": "c1",
        "type": "myflag"
      },
      {
        "name": "c2",
        "type": "myflag"
      }
    ]
  }
]
```

Getting following error from decoder.decode function

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SRCError { error: "Could not parse schema", side: Some("Failed to parse schema: Unknown type: myflag"), retriable: false, cached: true }', src/receiver.rs:96:23

I would appreciate any help with this

**Comment by gklijs** [comment]
It's likely related to https://github.com/gklijs/schema_registry_converter/issues/12. It's likely a problem in the avro-rs library, which should be fixed there. Another option would be to fork, remove the parts not used for this crate, and release with fix something like avro-minimal-rs. It's also possible it's already fixed in avro-rs.
The other solution, is to work around the problem like in https://github.com/gklijs/schema_registry_converter/tree/issue_12. I quicly tried rebasing, and that didn't work. So will try to look into it shotly.

**Comment by ajayrathore** [comment]
Thanks for looking into this issue, is there any other workaround? I need this feature for a project.

**Comment by gklijs** [comment]
I have nothing planned this weekend. I'll try to cut a release. The workaround would be included in the library if it's still needed.

**Comment by gklijs** [comment]
Could you try by depending on current master, so using 
`{ git = "https://github.com/gklijs/schema_registry_converter" }` I also added a test with both an enum and a fixed value, https://github.com/gklijs/schema_registry_converter/blob/082a9c3500fe321866cc6dfdda0d2e5e8444a75b/src/lib.rs#L791 ?

**Comment by ajayrathore** [comment]
Hi,
Apologies for being late in replying, I am still getting the same error on trying from master.
Can you check your fix with the schema I posted here?

**Comment by gklijs** [comment]
I should have looked better at your schema before. It's not in a format that's allowed by the schema registry, it should just have a record. Which means if you want to use the same enum twice you either have some code duplication, or need to replace those yourself.

**Comment by ajayrathore** [comment]
I had a second look as well and in fact you are correct, when I manually validate the schema, it gets rejected. I will follow your suggestion of duplicating the enum inside record type.
Closing the issue.
Thanks

**Comment by ajayrathore** [comment]
Hi Gerard,

I stumbled onto the same issue again, it seems rust lib cant parse the following schema as well

```
{
  "type": "record",
  "name": "mymsg",
  "namespace": "myns",
  "fields": [
    {
      "name": "myid",
      "type": "int"
    },
    {
      "name": "c1",
      "type": {
        "type": "enum",
        "name": "myflag",
        "symbols": [
          "A",
          "B",
          "C"
        ]
      }
    },
    {
      "name": "c2",
      "type": "myflag"
    }
  ]
}
```

Would you mind validating your fix against this?

**Comment by gklijs** [comment]
You had problems with the latest release, or with the current master using git dependency? There is also a new version of avro-rs so could also try updating that one. Which I had more time to finish the two features I want for the 2.0.0 release.

**Comment by ajayrathore** [comment]
Ok tried with both latest avro-rs-0.7 and schema-registry-converter from master and above schema does not work, getting following error. Looks like its coming from schema-converter and not avro-rs

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SRCError { error: "Could not parse schema", side: Some("Failed to parse schema: Unknown type: myflag"), retriable: false, cached: true }', src/receiver.rs:84:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by gklijs** [comment]
But in Java, and with schema registry it is working? Error is definitely from avro-rs, it's just 'catched' in schema-converter.

**Comment by ajayrathore** [comment]
Yes, its working from other language libs, this schema is valid, I can upload it successfully in schema registry.

**Comment by gklijs** [comment]
It's not without reason they aee about to add protobuf support. I might try to see how easy it is to fix. And try to fix in avro-rs if possible. Might also create my 'own' seperately from this lib. Or just implement protobuf and discourge the use of avro..

**Comment by ajayrathore** [comment]
I raised a PR for fixing this issue in avro-rs https://github.com/flavray/avro-rs/pull/118

Closing this issue here.
